cwd_saml_mapping.saml_login_redirect.*:
  type: config_entity
  label: CWD Login Redirect
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    roles:
      type: string
    redirect:
      type: string
